package com.wqg.yys_mapper;

import com.wqg.yys_pojo.UsersFans;
import com.wqg.yys_pojo.UsersFansExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface UsersFansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbggenerated
     */
    int countByExample(UsersFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbggenerated
     */
    int deleteByExample(UsersFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbggenerated
     */
    int insert(UsersFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbggenerated
     */
    int insertSelective(UsersFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbggenerated
     */
    List<UsersFans> selectByExample(UsersFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbggenerated
     */
    UsersFans selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UsersFans record, @Param("example") UsersFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UsersFans record, @Param("example") UsersFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UsersFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UsersFans record);
}
